# Generated by Django 3.2.13 on 2022-06-30 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gst_Model',
            fields=[
                ('Gst_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Gst_Prefix', models.CharField(default='GST0', max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('Description', models.CharField(blank=True, max_length=50)),
                ('Gst', models.IntegerField(blank=True)),
                ('Created_By', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
