# Generated by Django 3.2.13 on 2022-06-30 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Model',
            fields=[
                ('City_Code', models.AutoField(primary_key=True, serialize=False)),
                ('City_Prefix', models.CharField(default='CT00', max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('City_Name', models.CharField(max_length=50)),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Remark', models.CharField(blank=True, default=None, max_length=100)),
                ('Created_By', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
