# Generated by Django 3.2.13 on 2022-06-30 06:46

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('State', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_models',
            fields=[
                ('Customer_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Customer_Code_Display', models.IntegerField(blank=True, null=True)),
                ('customer_prefix', models.CharField(default='CUS0', max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_NO', models.BigIntegerField()),
                ('GSTIN', models.CharField(blank=True, max_length=25)),
                ('title', models.CharField(blank=True, choices=[('MR.', 'MR.'), ('MS.', 'MS.'), ('MRS.', 'MRS.')], default=('MR.', 'MR.'), max_length=25, null=True)),
                ('Billing_Name', models.CharField(blank=True, max_length=50)),
                ('Street_h_n', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('postalcode', models.IntegerField(blank=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('Name_shipping', models.CharField(blank=True, max_length=50)),
                ('title_ship', models.CharField(blank=True, choices=[('MR.', 'MR.'), ('MS.', 'MS.'), ('MRS.', 'MRS.')], default=('MR.', 'MR.'), max_length=50, null=True)),
                ('Street_h_n_ship', models.CharField(blank=True, max_length=50)),
                ('City_ship', models.CharField(blank=True, max_length=50)),
                ('postalcode_ship', models.IntegerField(blank=True)),
                ('country_ship', django_countries.fields.CountryField(max_length=2)),
                ('Remark', models.CharField(blank=True, default=None, max_length=50)),
                ('Place_Of_Supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='State_Mod', to='State.state_model')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='State.state_model')),
                ('state_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='State_Model', to='State.state_model')),
            ],
        ),
    ]
