# Generated by Django 3.2.13 on 2022-06-30 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyModel',
            fields=[
                ('Tally_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Data_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Tally_Prefix', models.CharField(default='TAL0', max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('Transection_No', models.CharField(max_length=50)),
                ('Tally_Name', models.CharField(max_length=50)),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Remark', models.CharField(blank=True, default=None, max_length=100)),
                ('Created_By', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
