# Generated by Django 3.2.13 on 2022-06-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '__first__'),
        ('Item_Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PO_No', models.AutoField(primary_key=True, serialize=False)),
                ('PO_Prefix', models.CharField(default='PO0', max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('PO_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('GST', models.CharField(blank=True, max_length=200, null=True)),
                ('Gst_percent', models.CharField(default='9%', max_length=20)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Expected_Arrival_date', models.DateField(blank=True, null=True)),
                ('Item_count', models.CharField(blank=True, max_length=50, null=True)),
                ('Remark', models.CharField(blank=True, max_length=500, null=True)),
                ('Created_By', models.CharField(blank=True, max_length=20, null=True)),
                ('Created_At', models.DateField(auto_now_add=True)),
                ('Updated_At', models.DateField(blank=True, null=True)),
                ('Supplier_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Supplier.supplier_models')),
            ],
            options={
                'default_related_name': '+',
            },
        ),
        migrations.CreateModel(
            name='Puchase_oreder_meterial',
            fields=[
                ('PO_meterial_id', models.AutoField(primary_key=True, serialize=False)),
                ('PO_line_Item', models.IntegerField(blank=True, null=True)),
                ('Item_quantity', models.IntegerField(blank=True, null=True)),
                ('Item_basePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Item_discount', models.IntegerField(blank=True, default='25', null=True)),
                ('Gst_type', models.CharField(blank=True, default='CGST', max_length=30, null=True)),
                ('Gst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Updated_At', models.DateField(blank=True, null=True)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Item_Master.item_model')),
                ('Purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PorchaseOrder.purchaseorder')),
            ],
        ),
    ]
