# Generated by Django 3.2.13 on 2022-06-30 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoLine_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False)),
                ('PoLine_Prefix', models.CharField(default='PLT0', max_length=20)),
                ('PoLine_No', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Remark', models.CharField(blank=True, default=None, max_length=100)),
                ('Created_By', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
