# Generated by Django 3.2.13 on 2022-06-30 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Model',
            fields=[
                ('Category_NO', models.AutoField(primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False)),
                ('Category_Prefix', models.CharField(default='CAT0', max_length=20)),
                ('Category_Name', models.CharField(max_length=25)),
                ('HSN_Code', models.CharField(max_length=20)),
                ('Category_Description', models.CharField(max_length=80)),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Remark', models.CharField(blank=True, default=None, max_length=100)),
                ('Created_By', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
