# Generated by Django 3.2.13 on 2022-06-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tally_master', '__first__'),
        ('Supplier', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_vouchers',
            fields=[
                ('Payment_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Prefix', models.CharField(default='PMT0', max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('Payment_amount', models.CharField(max_length=50)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('UPI', 'UPI'), ('Net-Banking', 'Net-Banking'), ('PhonePay', 'PhonePay'), ('Gpay', 'Gpay')], max_length=80)),
                ('Transection_No', models.CharField(max_length=100)),
                ('Bill_No', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('Supplier_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier_models')),
                ('Tally_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally', to='Tally_master.tallymodel')),
            ],
        ),
    ]
