# Generated by Django 3.2.13 on 2022-06-30 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UOM', '__first__'),
        ('Color', '0001_initial'),
        ('ITEM_Category', '0001_initial'),
        ('GST', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Model',
            fields=[
                ('Item_NO', models.AutoField(primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False)),
                ('Item_Prefix', models.CharField(default='ITM0', max_length=20)),
                ('Item_Name', models.CharField(max_length=25)),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Last_Change_Date', models.DateTimeField(auto_now_add=True)),
                ('Item_Description', models.CharField(max_length=100)),
                ('Item_Remark', models.CharField(blank=True, default=None, max_length=100)),
                ('Item_PCS', models.CharField(max_length=20)),
                ('Item_Size', models.CharField(max_length=20)),
                ('Item_Pirce', models.IntegerField()),
                ('Item_Image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Item_Image_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Item_Image_3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Item_Image_4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Color.color_model')),
                ('Created_By', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Item_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITEM_Category.category_model')),
                ('Item_GST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GST.gst_model')),
                ('UOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UOM.uom_model')),
            ],
        ),
    ]
