# Generated by Django 3.2.13 on 2022-06-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item_Master', '0001_initial'),
        ('Supplier', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('PR_No', models.AutoField(primary_key=True, serialize=False)),
                ('PR_Prefix', models.CharField(default='PR0', max_length=20)),
                ('PR_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, default='None', max_length=500, null=True)),
                ('Requistioner', models.CharField(default='None', max_length=200)),
                ('Item_Count', models.IntegerField()),
                ('GST', models.CharField(blank=True, max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Gst_percent', models.CharField(default='9%', max_length=20)),
                ('Expected_Arrival_date', models.DateField(blank=True, null=True)),
                ('Remark', models.CharField(blank=True, default='None', max_length=500, null=True)),
                ('Created_By', models.CharField(blank=True, max_length=20, null=True)),
                ('Created_At', models.DateField(auto_now_add=True)),
                ('Updated_By', models.CharField(blank=True, max_length=20, null=True)),
                ('Updated_At', models.DateField(blank=True, null=True)),
                ('Supplier_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supp_code', to='Supplier.supplier_models')),
            ],
        ),
        migrations.CreateModel(
            name='Puchase_request_meterial',
            fields=[
                ('PR_meterial_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default='False')),
                ('PR_line_Item', models.IntegerField(blank=True, null=True)),
                ('Unit_Measure', models.CharField(blank=True, max_length=50, null=True)),
                ('Item_quantity', models.IntegerField(default='10')),
                ('Item_basePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Gst_type', models.CharField(blank=True, max_length=20, null=True)),
                ('Gst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Updated_At', models.DateField(blank=True, null=True)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itm_code', to='Item_Master.item_model')),
                ('Purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puch_req', to='PorchaseRequest.purchaserequest')),
            ],
        ),
    ]
