# Generated by Django 3.2.13 on 2022-06-30 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('City', '__first__'),
        ('State', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_model',
            fields=[
                ('Branch_Code', models.AutoField(primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False)),
                ('Branch_Name', models.CharField(max_length=25)),
                ('Mobile_NO', models.BigIntegerField()),
                ('Branch_add', models.CharField(blank=True, max_length=50)),
                ('Remark', models.CharField(blank=True, default=None, max_length=100)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='City.city_model')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='State.state_model')),
            ],
        ),
    ]
